backend:
  name: github
  branch: main
  repo: waynevanson/waynevanson
media_folder: /src/media
public_folder: /public
collections:
  - name: posts
    label: Posts
    folder: /src/content/posts
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Summary
        name: summary
        widget: string
      - label: Body
        name: body
        widget: markdown
